apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-checkoutservice
  namespace: online-boutique
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: checkoutservice
  delay:
    latency: "300ms"
    correlation: "100"
    jitter: "0ms"
  duration: "5m"
