apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-paymentservice-cpu
  namespace: online-boutique
spec:
  mode: one
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: paymentservice
  stressors:
    cpu:
      workers: 1
      load: 80
  duration: "5m"
