apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: online-boutique-frontend-network-delay
  namespace: online-boutique
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: frontend
  delay:
    latency: "250ms"
    correlation: "50"
    jitter: "50ms"
  duration: "5m"
