apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: online-boutique-productcatalog-pod-kill
  namespace: online-boutique
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: productcatalogservice
  duration: "60s"
