apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: sockshop-catalogue-pod-kill
  namespace: sock-shop
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      name: catalogue
  duration: "60s"

